import { APP_BASELINE, APP_NAME, APP_OWNER, APP_TRADEMARK, APP_VERSION, APP_YEAR, buildId } from "@/lib/version";

const FEATURES: [string, string][] = [
  ["Daily rhythm", "Evening check-in, class log for every timetable lesson with homework yes/no, prayer log with honest late entries, points, streaks and levels."],
  ["Learning", "Curriculum topics by grade, AI practice sets, daily recall quizzes, spaced review, SAT and ACT tracks, Arabic Ministry subjects, Quran memorisation."],
  ["School files", "PDFs and photos from the class groups read once by the AI, turned into tasks and into on-system practice of the teacher's own worksheet."],
  ["Planning", "A prepared week of quizzes per child, WhatsApp import and archive, school website checks, school days off."],
  ["Coach", "Weekly wellbeing checks (WHO-5 and short scales), a confidential coach chat with safety escalation, a weekly coach report, learner profile and interests, clinician-facing summaries."],
  ["Discipline and fairness", "Allowance earned through basics, snap tasks with AI screening and parent approval, catch-up windows for missed days, integrity signals as questions, Straight talk honesty check, timed one-attempt checkpoints."],
  ["Family", "Two parents with their own logins and channels, custody days, daily report by Telegram and browser notifications, access log, consent-based location, home and school places."],
];

/** Version, what is in this release, the agreement, and the ownership notices. */
export function About({ role }: { role: "parent" | "student" }) {
  return (
    <div className="space-y-4">
      <section className="card space-y-1">
        <div className="flex items-center gap-3">
          <span className="text-4xl">🎓</span>
          <div>
            <h2 className="h2">{APP_NAME} <span className="badge ml-1">v{APP_VERSION}</span></h2>
            <p className="text-xs muted">{APP_BASELINE} · build {buildId()}</p>
          </div>
        </div>
        <p className="text-sm muted">A family study portal: routine, learning, wellbeing and fairness in one place, with an AI coach that reports to the parents and keeps the child&apos;s confidences unless there is danger.</p>
      </section>

      {role === "parent" && (
        <section className="card space-y-2">
          <h3 className="font-bold">What version 1.0 includes</h3>
          <ul className="text-sm space-y-1">
            {FEATURES.map(([k, v]) => <li key={k}><b>{k}.</b> <span className="muted">{v}</span></li>)}
          </ul>
          <p className="text-xs muted">Version 1.0 is the baseline. Later changes are tuning on top of it and carry 1.x numbers.</p>
        </section>
      )}

      <section className="card space-y-2 text-sm">
        <h3 className="font-bold">Agreement</h3>
        <p>{APP_NAME} is provided for the private use of the family it was set up for. By using it you agree to the following.</p>
        <ul className="list-disc pl-5 space-y-1 muted">
          <li><b className="text-ink">AI content.</b> Quizzes, explanations, file readings, coach reports and clinician summaries are generated by an AI model. They can be wrong. They are not medical, psychological or educational advice, and they do not replace teachers, doctors or counsellors.</li>
          <li><b className="text-ink">Wellbeing and safety.</b> The coach chat and wellbeing checks are confidential to the child, with one exception: signs of danger are passed to the parents. In an emergency call 123 (Egypt) or the child helpline 16000.</li>
          <li><b className="text-ink">Data.</b> Check-ins, logs, pictures, files, locations and chat text are stored for this family only and shown to its parents as this app describes. Pictures from snap tasks are deleted after 30 days. Nothing is sold or shared outside the family.</li>
          <li><b className="text-ink">Fair use.</b> The allowance, integrity signals and checkpoints are aids for a conversation between parent and child, not verdicts.</li>
          <li><b className="text-ink">No warranty.</b> The software is provided as is, without warranty of any kind. The owner is not liable for decisions taken on the basis of its output.</li>
        </ul>
      </section>

      <section className="card space-y-1 text-sm">
        <h3 className="font-bold">Copyright and trademark</h3>
        <p>© {APP_YEAR} {APP_OWNER}. All rights reserved.</p>
        <p>{APP_NAME}™ and the {APP_TRADEMARK}™ name are trademarks of {APP_TRADEMARK}, {APP_OWNER}.</p>
        <p className="muted text-xs">The design, text, prompts, rules, scoring methods and source code of this application, as developed up to version {APP_VERSION}, are the property of {APP_OWNER} and {APP_TRADEMARK}. No part may be copied, redistributed or used to build another product without written permission. Third-party libraries remain under their own licences.</p>
      </section>
    </div>
  );
}
