-- Clinician-facing summaries generated by the parent for a mental-health professional.
create table public.clinician_reports (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  family_id uuid not null references public.families(id) on delete cascade,
  scope text not null check (scope in ('standard', 'with_chat_themes')),
  reason text,                            -- parent's reason for referral, in their words
  period_start date not null,
  period_end date not null,
  content_md text not null,
  data jsonb not null,                    -- the raw tables the narrative was built from
  model text,
  created_at timestamptz not null default now()
);
create index clinician_reports_student_idx on public.clinician_reports(student_id, created_at desc);
alter table public.clinician_reports enable row level security;
create policy clinician_reports_parent on public.clinician_reports for all to authenticated
  using (family_id = app_private.current_family_id() and app_private.current_role_is('parent'))
  with check (family_id = app_private.current_family_id() and app_private.current_role_is('parent'));
-- The child can see that a report including chat themes exists (transparency), not its content.
create policy clinician_reports_student_meta on public.clinician_reports for select to authenticated
  using (student_id = auth.uid());
