-- Egyptian Ministry of Education subjects taught in Arabic: Arabic, Religion (Islamic), Arabic Social Studies.
alter table public.topics add column language text not null default 'en' check (language in ('en', 'ar'));
alter table public.quizzes add column language text not null default 'en' check (language in ('en', 'ar'));

insert into public.topics (family_id, track, grade, subject, unit, name, description, sort, language) values
-- Grade 8 Arabic (الصف الثاني الإعدادي)
(null,'school',8,'Arabic','نحو','رفع الفعل المضارع وعلاماته',null,1,'ar'),
(null,'school',8,'Arabic','نحو','نصب الفعل المضارع وأدوات النصب',null,2,'ar'),
(null,'school',8,'Arabic','نحو','جزم الفعل المضارع وأدوات الجزم',null,3,'ar'),
(null,'school',8,'Arabic','نحو','الأفعال الخمسة وإعرابها',null,4,'ar'),
(null,'school',8,'Arabic','نحو','المفعول المطلق',null,5,'ar'),
(null,'school',8,'Arabic','نحو','المفعول لأجله',null,6,'ar'),
(null,'school',8,'Arabic','نحو','الحال',null,7,'ar'),
(null,'school',8,'Arabic','نحو','التمييز',null,8,'ar'),
(null,'school',8,'Arabic','قراءة','الفكرة الرئيسية والأفكار الجزئية في النص',null,9,'ar'),
(null,'school',8,'Arabic','قراءة','المفردات: المرادف والمضاد والجمع والمفرد',null,10,'ar'),
(null,'school',8,'Arabic','نصوص','تذوق النص الشعري: التشبيه والاستعارة',null,11,'ar'),
(null,'school',8,'Arabic','إملاء','الهمزة المتوسطة والمتطرفة',null,12,'ar'),
(null,'school',8,'Arabic','إملاء','التاء المربوطة والمفتوحة والألف اللينة',null,13,'ar'),
(null,'school',8,'Arabic','تعبير','كتابة الفقرة والموضوع الوظيفي',null,14,'ar'),
-- Grade 10 Arabic (الصف الأول الثانوي)
(null,'school',10,'Arabic','نحو','الجملة الاسمية وأنواع الخبر',null,1,'ar'),
(null,'school',10,'Arabic','نحو','كان وأخواتها',null,2,'ar'),
(null,'school',10,'Arabic','نحو','إن وأخواتها',null,3,'ar'),
(null,'school',10,'Arabic','نحو','كاد وأخواتها (أفعال المقاربة والشروع)',null,4,'ar'),
(null,'school',10,'Arabic','نحو','الفاعل ونائب الفاعل',null,5,'ar'),
(null,'school',10,'Arabic','نحو','المفعول به وأنواعه',null,6,'ar'),
(null,'school',10,'Arabic','بلاغة','التشبيه وأنواعه',null,7,'ar'),
(null,'school',10,'Arabic','بلاغة','الاستعارة التصريحية والمكنية',null,8,'ar'),
(null,'school',10,'Arabic','بلاغة','الكناية',null,9,'ar'),
(null,'school',10,'Arabic','بلاغة','المحسنات البديعية: الطباق والمقابلة والجناس',null,10,'ar'),
(null,'school',10,'Arabic','أدب','العصر الجاهلي: خصائص الشعر والمعلقات',null,11,'ar'),
(null,'school',10,'Arabic','أدب','النثر الجاهلي: الخطابة والحكم والأمثال',null,12,'ar'),
(null,'school',10,'Arabic','أدب','أثر الإسلام في الشعر والنثر',null,13,'ar'),
(null,'school',10,'Arabic','نصوص','تحليل النص الشعري: الفكرة والعاطفة والصور',null,14,'ar'),
(null,'school',10,'Arabic','قراءة','فهم المقروء والتلخيص',null,15,'ar'),
(null,'school',10,'Arabic','تعبير','الموضوع الوظيفي والإبداعي',null,16,'ar'),
-- Grade 8 Religion (التربية الإسلامية)
(null,'school',8,'Religion','قرآن كريم','تفسير الآيات المقررة: القيم والآداب',null,1,'ar'),
(null,'school',8,'Religion','حديث شريف','أحاديث الصدق والأمانة وحسن الخلق',null,2,'ar'),
(null,'school',8,'Religion','عقيدة','الإيمان بالله وأسماؤه الحسنى وصفاته',null,3,'ar'),
(null,'school',8,'Religion','عقيدة','الإيمان بالقضاء والقدر',null,4,'ar'),
(null,'school',8,'Religion','سيرة','الهجرة النبوية وبناء الدولة في المدينة',null,5,'ar'),
(null,'school',8,'Religion','سيرة','غزوتا بدر وأحد ودروسهما',null,6,'ar'),
(null,'school',8,'Religion','فقه','الصلاة: شروطها وأركانها وسننها',null,7,'ar'),
(null,'school',8,'Religion','فقه','الصيام: أحكامه وآدابه',null,8,'ar'),
(null,'school',8,'Religion','فقه','الزكاة والصدقة',null,9,'ar'),
(null,'school',8,'Religion','أخلاق','بر الوالدين وصلة الرحم وحقوق الجار',null,10,'ar'),
-- Grade 10 Religion
(null,'school',10,'Religion','قرآن كريم','تفسير الآيات المقررة وهداياتها',null,1,'ar'),
(null,'school',10,'Religion','حديث شريف','أحاديث في المعاملات والعمل والإتقان',null,2,'ar'),
(null,'school',10,'Religion','عقيدة','أركان الإيمان والتوحيد',null,3,'ar'),
(null,'school',10,'Religion','عقيدة','الإيمان باليوم الآخر',null,4,'ar'),
(null,'school',10,'Religion','سيرة','الخلفاء الراشدون: أبو بكر وعمر',null,5,'ar'),
(null,'school',10,'Religion','سيرة','الخلفاء الراشدون: عثمان وعلي',null,6,'ar'),
(null,'school',10,'Religion','فقه','الطهارة والصلاة وأحكام السهو',null,7,'ar'),
(null,'school',10,'Religion','فقه','الزكاة والصوم والحج',null,8,'ar'),
(null,'school',10,'Religion','فقه','المعاملات: البيع والربا والكسب الحلال',null,9,'ar'),
(null,'school',10,'Religion','أخلاق','الصدق والوفاء والتسامح والوسطية',null,10,'ar'),
-- Grade 8 Arabic Social Studies (الدراسات الاجتماعية: تاريخ وجغرافيا)
(null,'school',8,'Arabic Social Studies','تاريخ','الفتح الإسلامي لمصر',null,1,'ar'),
(null,'school',8,'Arabic Social Studies','تاريخ','مصر في عصر الولاة',null,2,'ar'),
(null,'school',8,'Arabic Social Studies','تاريخ','الدولة الطولونية والدولة الإخشيدية',null,3,'ar'),
(null,'school',8,'Arabic Social Studies','تاريخ','الدولة الفاطمية',null,4,'ar'),
(null,'school',8,'Arabic Social Studies','تاريخ','الدولة الأيوبية وصلاح الدين والحروب الصليبية',null,5,'ar'),
(null,'school',8,'Arabic Social Studies','تاريخ','دولة المماليك والتصدي للمغول',null,6,'ar'),
(null,'school',8,'Arabic Social Studies','تاريخ','مصر تحت الحكم العثماني',null,7,'ar'),
(null,'school',8,'Arabic Social Studies','جغرافيا','الوطن العربي: الموقع والمساحة والحدود',null,8,'ar'),
(null,'school',8,'Arabic Social Studies','جغرافيا','تضاريس الوطن العربي',null,9,'ar'),
(null,'school',8,'Arabic Social Studies','جغرافيا','مناخ الوطن العربي والنبات الطبيعي',null,10,'ar'),
(null,'school',8,'Arabic Social Studies','جغرافيا','سكان الوطن العربي وموارده',null,11,'ar'),
-- Grade 10 Arabic Social Studies
(null,'school',10,'Arabic Social Studies','تاريخ','الحضارة المصرية القديمة: الدولة القديمة والوسطى',null,1,'ar'),
(null,'school',10,'Arabic Social Studies','تاريخ','الحضارة المصرية القديمة: الدولة الحديثة',null,2,'ar'),
(null,'school',10,'Arabic Social Studies','تاريخ','مظاهر الحضارة المصرية: الحكم والدين والعلوم والفنون',null,3,'ar'),
(null,'school',10,'Arabic Social Studies','تاريخ','حضارات بلاد الرافدين والشام',null,4,'ar'),
(null,'school',10,'Arabic Social Studies','تاريخ','الحضارة اليونانية والرومانية ومصر',null,5,'ar'),
(null,'school',10,'Arabic Social Studies','جغرافيا','مصر: الموقع والأهمية والحدود',null,6,'ar'),
(null,'school',10,'Arabic Social Studies','جغرافيا','تضاريس مصر',null,7,'ar'),
(null,'school',10,'Arabic Social Studies','جغرافيا','مناخ مصر وأقاليمه',null,8,'ar'),
(null,'school',10,'Arabic Social Studies','جغرافيا','نهر النيل والموارد المائية',null,9,'ar'),
(null,'school',10,'Arabic Social Studies','جغرافيا','سكان مصر والتنمية',null,10,'ar');
